twitter:
  consumer_key: "7zmoyw3GCj824jDIRozJHz2Vq"
  consumer_secret: "SJUZz6kT4UlEzgcq35W4CGvVy43dJGZ2FQnkEIyWnHDAtJUx2m"
  access_token: "767256409-LCM77QtboX4Jjr1zHA2kISIJSGQBMIFKZOdwXguv"
  access_token_secret: "H7X7QYSBXanvx93nVhJag8ZeKfzBl7hZLCcItkok2l6FO"